export const theme = {
  colors: {
    primary: '#0071e3',
    secondary: '#86868b',
    tertiary: '#aeaeb2',
    background: '#f5f5f7',
    backgroundLight: '#fafafa',
    backgroundGray: '#e5e5e7',
    border: '#e5e5e7',
    borderLight: '#d1d1d6',
    success: '#34c759',
    error: '#ff3b30',
    errorBg: '#fff0f0',
    errorBorder: '#ffcccc',
    textPrimary: '#1d1d1f',
    textSecondary: '#86868b',
    textTertiary: '#aeaeb2',
    textMuted: '#c7c7cc',
  },
  fonts: {
    primary: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", "Segoe UI", Roboto, sans-serif',
    mono: '"SF Mono", "SF Mono Mono", "Menlo", "Consolas", monospace',
  },
  borderRadius: {
    sm: '6px',
    md: '10px',
    lg: '16px',
    xl: '20px',
  },
  spacing: {
    xs: '6px',
    sm: '10px',
    md: '16px',
    lg: '20px',
    xl: '24px',
    xxl: '32px',
  },
};

export const styles = {
  container: {
    width: '100%',
    minHeight: '100vh',
    fontFamily: theme.fonts.primary,
    backgroundColor: theme.colors.background,
    color: theme.colors.textPrimary,
    lineHeight: 1.5,
  },
  main: {
    width: '100%',
    maxWidth: '1120px',
    margin: '0 auto',
    padding: 'clamp(40px, 6vw, 80px) clamp(24px, 4vw, 48px)',
    boxSizing: 'border-box' as const,
  },
  card: {
    background: 'rgba(255, 255, 255, 0.85)',
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    borderRadius: theme.borderRadius.xl,
    padding: '32px',
    border: '1px solid rgba(229, 229, 231, 0.6)',
    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.04)',
  },
  button: {
    primary: {
      background: '#0071e3',
      color: 'white',
      border: 'none',
      padding: '10px 22px',
      borderRadius: theme.borderRadius.sm,
      fontSize: '14px',
      fontWeight: '500' as const,
      cursor: 'pointer',
      letterSpacing: '-0.01em',
    },
    secondary: {
      background: 'rgba(229, 229, 231, 0.5)',
      color: theme.colors.textPrimary,
      border: 'none',
      padding: '10px 22px',
      borderRadius: theme.borderRadius.sm,
      fontSize: '14px',
      fontWeight: '500' as const,
      cursor: 'pointer',
      letterSpacing: '-0.01em',
    },
  },
  textarea: {
    width: '100%',
    background: 'rgba(245, 245, 247, 0.6)',
    border: '1px solid rgba(229, 229, 231, 0.5)',
    borderRadius: theme.borderRadius.md,
    padding: theme.spacing.md,
    fontFamily: theme.fonts.mono,
    fontSize: '14px',
    lineHeight: 1.5,
    resize: 'vertical' as const,
    color: theme.colors.textPrimary,
  },
  input: {
    width: '100%',
    padding: theme.spacing.sm,
    borderRadius: theme.borderRadius.sm,
    border: '1px solid rgba(229, 229, 231, 0.5)',
    backgroundColor: 'rgba(245, 245, 247, 0.6)',
    color: theme.colors.textPrimary,
    fontSize: '14px',
    fontFamily: theme.fonts.mono,
  },
};
