export const theme = {
  colors: {
    primary: '#1a1a1a',
    secondary: '#666',
    background: '#ffffff',
    backgroundLight: '#fafafa',
    backgroundGray: '#f5f5f5',
    border: '#e0e0e0',
    borderLight: '#eaeaea',
    success: '#388e3c',
    error: '#d32f2f',
    errorBg: '#ffebee',
    errorBorder: '#ffcdd2',
    textPrimary: '#1a1a1a',
    textSecondary: '#666',
    textTertiary: '#888',
    textMuted: '#999',
  },
  fonts: {
    primary: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    mono: 'monospace',
  },
  borderRadius: {
    sm: '4px',
    md: '6px',
    lg: '8px',
  },
  spacing: {
    xs: '8px',
    sm: '12px',
    md: '16px',
    lg: '20px',
    xl: '24px',
  },
};

export const styles = {
  container: {
    width: '100%',
    minHeight: '100vh',
    fontFamily: theme.fonts.primary,
    backgroundColor: theme.colors.background,
    color: theme.colors.textPrimary,
    lineHeight: 1.5,
  },
  main: {
    width: '100%',
    maxWidth: '1400px',
    margin: '0 auto',
    padding: 'clamp(20px, 4vw, 40px) clamp(16px, 3vw, 24px)',
    boxSizing: 'border-box' as const,
  },
  card: {
    background: theme.colors.background,
    borderRadius: theme.borderRadius.lg,
    padding: theme.spacing.xl,
    border: `1px solid ${theme.colors.border}`,
  },
  button: {
    primary: {
      background: theme.colors.primary,
      color: 'white',
      border: 'none',
      padding: '10px 20px',
      borderRadius: theme.borderRadius.sm,
      fontSize: '14px',
      fontWeight: '500' as const,
      cursor: 'pointer',
      transition: 'all 0.2s ease',
    },
    secondary: {
      background: theme.colors.backgroundGray,
      color: theme.colors.secondary,
      border: 'none',
      padding: '10px 20px',
      borderRadius: theme.borderRadius.sm,
      fontSize: '14px',
      fontWeight: '500' as const,
      cursor: 'pointer',
      transition: 'all 0.2s ease',
    },
  },
  textarea: {
    width: '100%',
    background: theme.colors.backgroundLight,
    border: `1px solid ${theme.colors.border}`,
    borderRadius: theme.borderRadius.sm,
    padding: theme.spacing.md,
    fontFamily: theme.fonts.mono,
    fontSize: '14px',
    lineHeight: 1.5,
    resize: 'vertical' as const,
    color: theme.colors.textPrimary,
  },
  input: {
    width: '100%',
    padding: theme.spacing.sm,
    borderRadius: theme.borderRadius.sm,
    border: `1px solid ${theme.colors.border}`,
    backgroundColor: theme.colors.backgroundLight,
    color: theme.colors.textPrimary,
    fontSize: '14px',
    fontFamily: theme.fonts.mono,
  },
};